# Generated by Django 4.2.1 on 2023-07-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="bairro",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="imovel",
            name="numero",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="ano_construcao",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel", name="ano_reforma", field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel", name="km", field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="valor_aluguel",
            field=models.FloatField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="valor_condominio",
            field=models.FloatField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel", name="valor_iptu", field=models.FloatField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="valor_maximo_interesse",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="valor_minimo_interesse",
            field=models.IntegerField(default=""),
        ),
        migrations.AlterField(
            model_name="imovel",
            name="valor_venda",
            field=models.FloatField(default=""),
        ),
    ]
