# Generated by Django 4.2.1 on 2023-07-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0002_imovel_bairro_imovel_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="cep",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="imovel",
            name="pt_referencia",
            field=models.CharField(default="", max_length=200),
        ),
    ]
