# Generated by Django 4.2.1 on 2023-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imoveis", "0003_imovel_cep_imovel_pt_referencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="cidade",
            field=models.CharField(default="", max_length=20),
        ),
    ]
